version: "3"
services:

redis:
  image: "redis:alpine"
  hostname: "redis"

  ports:
      - "6379:6379"

  volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  command: [ "redis-server", "/redis.conf" ]


zookeeper:
  image: "zookeeper:3.4.9"
  hostname: "zookeeper1"

  ports:
    - "2181:2181"

  volumes:
    - $PWD/zookeeper1/data:/data
    - $PWD/zookeeper1/datalog:/datalog

kafka1:
  image: confluentinc/cp-kafka:5.5.1
  hostname: kafka1

  ports:
    - "9092:9092"

  volumes:
    - $PWD/kafka1/data:/var/lib/kafka/data

  depends_on:
    - zookeeper1
